AllCops:
  TargetRubyVersion: 2.4
Metrics/LineLength:
  Max: 120
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/Documentation:
  Enabled: false
